package luyao.direct.model.entity

import luyao.direct.ext.newUID


data class SearchEngineList(val version: Int, val schemes: List<SearchEngine>)

data class SearchEngine(
    val id: String, val isSearch: Int, val label: String, val packageName: String,
    val desc: String, val searchUrl: String, val scheme: String, val order: Int, val iconUrl: String
)

val engineList = SearchEngineList(
    10, mutableListOf(
        SearchEngine(
            newUID(),
            1,
            "必应",
            "",
            "",
            "https://www.bing.com/search?q=%s",
            "",
            1,
            "http://apk.luyao.tech/image/search/search_bing.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "谷歌",
            "",
            "",
            "https://google.com/search?q=%s",
            "",
            0,
            "http://apk.luyao.tech/image/search/search_google.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "百度",
            "",
            "",
            "https://www.baidu.com/s?wd=%s",
            "",
            4,
            "http://apk.luyao.tech/image/search/search_baidu.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "头条",
            "",
            "",
            "https://so.toutiao.com/search?&keyword=%s",
            "",
            3,
            "http://apk.luyao.tech/image/search/search_bytedance.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "抖音",
            "com.ss.android.ugc.aweme",
            "",
            "https://www.douyin.com/search/%s?source=normal_search",
            "snssdk1128://search/result?keyword=%s",
            11,
            "http://apk.luyao.tech/image/search/search_douyin.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "知乎",
            "com.zhihu.android",
            "",
            "https://www.zhihu.com/search?q=%s&type=content",
            "zhihu://search?q=%s",
            2,
            "http://apk.luyao.tech/image/search/search_zhihu.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "搜狗",
            "",
            "",
            "https://www.sogou.com/web?query=%s",
            "",
            5,
            "http://apk.luyao.tech/image/search/search_sougou.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "Bilibili",
            "tv.danmaku.bili",
            "",
            "https://m.bilibili.com/search?keyword=%s",
            "bilibili://search?keyword=%s",
            6,
            "http://apk.luyao.tech/image/search/search_bilibili.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "淘宝",
            "com.taobao.taobao",
            "",
            "https://s.m.taobao.com/h5?q=%s",
            "taobao://s.m.taobao.com/h5?q=%s",
            7,
            "http://apk.luyao.tech/image/search/search_taobao.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "高德",
            "com.autonavi.minimap",
            "",
            "https://ditu.amap.com/search?query=%s",
            "androidamap://arroundpoi?sourceApplication=Direct&keywords=%s&dev=0",
            8,
            "http://apk.luyao.tech/image/search/search_amap.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "微博",
            "com.sina.weibo",
            "",
            "https://m.weibo.cn/search?containerid=100103type=1&q=%s",
            "sinaweibo://searchall?q=%s",
            9,
            "http://apk.luyao.tech/image/search/search_weibo.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "拼多多",
            "com.xunmeng.pinduoduo",
            "",
            "https://m.pinduoduo.com/",
            "pinduoduo://com.xunmeng.pinduoduo/search_result.html?search_key=%s",
            10,
            "http://apk.luyao.tech/image/search/search_pdd.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "百度地图",
            "com.baidu.BaiduMap",
            "",
            "https://map.baidu.com/mobile/webapp/index/index/#search/search/qt=s&wd=%s",
            "bdapp://map/place/search?query=%s",
            12,
            "http://apk.luyao.tech/image/search/search_bd_map.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "有道词典",
            "com.youdao.dict",
            "",
            "https://m.youdao.com/dict?le=eng&q=%s",
            "yddict://dict/query?q=%s",
            13,
            "http://apk.luyao.tech/image/search/search_youdao_dict.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "应用商店",
            "com.android.settings",
            "",
            "",
            "market://search?q=%s",
            14,
            "http://apk.luyao.tech/image/search/search_app_store.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "欧路词典",
            "",
            "",
            "https://dict.eudic.net/mdicts/en/%s",
            "eudic://dict/%s",
            15,
            "http://apk.luyao.tech/image/search/searh_oulu_dict.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "小红书",
            "com.xingin.xhs",
            "",
            "",
            "xhsdiscover://search/result?keyword=%s",
            16,
            "http://apk.luyao.tech/image/search/search_xhs.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "快手",
            "com.smile.gifmaker",
            "",
            "",
            "kwai://search?keyword=%s",
            17,
            "http://apk.luyao.tech/image/search/search_kuaishou.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "豆瓣",
            "com.douban.frodo",
            "",
            "",
            "douban://douban.com/search?q=%s",
            18,
            "http://apk.luyao.tech/image/search/search_douban.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "大众点评",
            "com.dianping.v1",
            "",
            "",
            "dianping://searchshoplist?keyword=%s",
            19,
            "http://apk.luyao.tech/image/search/search_dianping.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "美团",
            "com.sankuai.meituan",
            "",
            "",
            "imeituan://www.meituan.com/search?q=%s",
            20,
            "http://apk.luyao.tech/image/search/search_meituan.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "京东",
            "com.jingdong.app.mall",
            "",
            "https://search.jd.com/Search?keyword=%s",
            "openapp.jdmobile://virtual?params={\"des\":\"productList\",\"keyWord\":\"%s\",\"from\":\"search\",\"category\":\"jump\"}",
            21,
            "http://apk.luyao.tech/image/search/search_jd.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "微博国际版",
            "com.weico.international",
            "",
            "",
            "weibointernational://search?keyword=%s",
            22,
            "http://apk.luyao.tech/image/search/search_weibo_international.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "拼多多百亿补贴",
            "com.xunmeng.pinduoduo",
            "",
            "",
            "pinduoduo://com.xunmeng.pinduoduo/brand_activity_search_result.html?ten_billion_scene=&query=%s",
            23,
            "http://apk.luyao.tech/image/search/search_pdd.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "M浏览器",
            "cn.nr19.mbrowser",
            "",
            "",
            "m:search=%s",
            24,
            "http://apk.luyao.tech/image/search/search_m_browser.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "支付宝",
            "com.eg.android.AlipayGphone",
            "",
            "",
            "alipays://platformapi/startapp?appId=20001003&actionSrc=share&keyword=%s",
            25,
            "http://apk.luyao.tech/image/search/search_zhifubao.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "雪豹速清",
            "com.idaodan.clean.master",
            "",
            "",
            "search://www.idaodan.cn/search?keyword=%s",
            26,
            "http://apk.luyao.tech/image/search/search_xuebao.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "白马地图",
            "me.gfuil.bmap",
            "",
            "",
            "bmap://?action=search&keyword=%s",
            27,
            "http://apk.luyao.tech/image/search/search_bmap.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "百度地图",
            "com.baidu.BaiduMap",
            "",
            "",
            "bdapp://map/geocoder?src=andr.baidu.openAPIdemo&address=%s",
            28,
            "http://apk.luyao.tech/image/search/search_bdmap.png"
        ),
        SearchEngine(
            newUID(),
            1,
            "小红书商品",
            "com.xingin.xhs",
            "",
            "",
            "xhsdiscover://instore_search/result?keyword=%s",
            29,
            "http://apk.luyao.tech/image/search/search_xhs.png"
        )
    )
)

val engineListGp = SearchEngineList(
    10, mutableListOf(
        SearchEngine(
            "91dd3c4d-bee5-40d8-87e9-8e0fbb881e0a",
            1,
            "谷歌",
            "",
            "",
            "https://google.com/search?q=%s",
            "",
            0,
            "http://apk.luyao.tech/image/search/search_google.png"
        ),
        SearchEngine(
            "67fd4c11-532f-4976-93f7-af728d5c5efc",
            1,
            "必应",
            "",
            "",
            "https://www.bing.com/search?q=%s",
            "",
            1,
            "http://apk.luyao.tech/image/search/search_bing.png"
        ),
        SearchEngine(
            "f5a06117-790d-45da-9fd6-e8d0b223174f",
            1,
            "百度",
            "",
            "",
            "https://www.baidu.com/s?wd=%s",
            "",
            4,
            "http://apk.luyao.tech/image/search/search_baidu.png"
        ),
        SearchEngine(
            "b4527d99-0f45-4fd7-81ed-16fc70fc3509",
            1,
            "搜狗",
            "",
            "",
            "https://www.sogou.com/web?query=%s",
            "",
            5,
            "http://apk.luyao.tech/image/search/search_sougou.png"
        )
    )
)

fun SearchEngine.toNewSearchEngine(showPanel:Int = 0) = NewDirectEntity(
    id = newUID(),
    isSearch = isSearch,
    label = label,
    packageName = packageName,
    desc = desc,
    searchUrl = searchUrl,
    scheme = scheme,
    order = order,
    iconUrl = iconUrl,
    showPanel = showPanel
)